### ISSUE TITLE
Roadmap for future releases

### ISSUE THREAD

**Issue by mesozoic** [gtalarico/pyairtable#249]
The following is a rough proposal for which features we plan to add to pyAirtable, loosely grouped into releases. Priorities can shift over time, and anyone who wants to see a particular feature implemented faster is welcome to submit pull requests for review. I'm comfortable with the scope of the 1.5.0 and 2.0.0 releases; everything past there is a bit more speculative, but I have proofs of concept for at least some of it.

This document assumes we are using [semantic versioning](https://semver.org/), and that existing APIs can *only* be broken if there is a major version number change. As such, we may be more cautious about implementing new endpoints (or accepting PRs for new endpoints) if the design of that API merits discussion, because we'll commit to supporting new APIs for at least one major version.

Tagging other recent code contributors for input. @bapcon @goksan @larsakerson @nicohood

## 1.5 (released May '23)

This release will focus on bug fixes, quick wins, and reducing the open issue count.

- [x] Documentation typos and fixes (see [197](https://github.com/gtalarico/pyairtable/issues/197))
- [x] Implement continuous integration with type checking (see [195](https://github.com/gtalarico/pyairtable/issues/195), [217](https://github.com/gtalarico/pyairtable/issues/217), [239](https://github.com/gtalarico/pyairtable/issues/239), [240](https://github.com/gtalarico/pyairtable/issues/240), [241](https://github.com/gtalarico/pyairtable/issues/241), [242](https://github.com/gtalarico/pyairtable/issues/242))
- [x] #243
- [x] #182
- [x] #250 (see [190](https://github.com/gtalarico/pyairtable/issues/190))
- [x] #247 (see [203](https://github.com/gtalarico/pyairtable/issues/203), [210](https://github.com/gtalarico/pyairtable/issues/210), [222](https://github.com/gtalarico/pyairtable/issues/222))
- [x] #255 (see [209](https://github.com/gtalarico/pyairtable/issues/209), [216](https://github.com/gtalarico/pyairtable/issues/216))
- [x] #194

## 2.0 (July '23)

This release will be our chance to make any breaking API changes, such as changes to default behavior or return types. We will also implement stricter typing across the library, which might break CI for downstream code that does its own type checking, and support every field type in the ORM.

- [x] #261
- [x] #260
- [x] #262
- [x] Remove (or fully implement) `validate_type=` parameter to `Field` constructor
- [x] #263 (see [202](https://github.com/gtalarico/pyairtable/issues/202))
- [x] Use `dataclasses` or `TypedDict` on all return values
- [x] #251
- [x] #267
- [x] #272
- [x] #273 for [Get user ID & scopes](https://airtable.com/developers/web/api/get-user-id-scopes)
- [x] #274 
- [x] #277
- [x] #281
- [x] #282 
- [x] #268 
- [x] ORM: Support passing LinkField by name (see [176](https://github.com/gtalarico/pyairtable/issues/176), [200](https://github.com/gtalarico/pyairtable/issues/200))

## 2.1

Just a plain ol' feature release.

- [x] Webhooks (see [208](https://github.com/gtalarico/pyairtable/issues/208), [236](https://github.com/gtalarico/pyairtable/issues/236))
  - [List webhook payloads](https://airtable.com/developers/web/api/list-webhook-payloads)
  - [List webhooks](https://airtable.com/developers/web/api/list-webhooks)
  - [Create a webhook](https://airtable.com/developers/web/api/create-a-webhook)
  - [Delete a webhook](https://airtable.com/developers/web/api/delete-a-webhook)
  - [Enable/disable webhook notifications](https://airtable.com/developers/web/api/enable-disable-webhook-notifications)
  - [Refresh a webhook](https://airtable.com/developers/web/api/refresh-a-webhook)

## 2.2

Build a sustainable pattern for retrieving with Airtable metadata, which involves a lot of deeply nested object structures.

- [x] Enterprise: Read enterprise information
  - [Get enterprise](https://airtable.com/developers/web/api/get-enterprise)
  - [Get user by email](https://airtable.com/developers/web/api/get-user-by-email)
  - [Get user by id](https://airtable.com/developers/web/api/get-user-by-id)
  - [Get user group](https://airtable.com/developers/web/api/get-user-group)
- [x] Metadata APIs that return typed dataclasses instead of dicts
- [x] Metadata: Read base, table, field schemas (see [204](https://github.com/gtalarico/pyairtable/issues/204), [230](https://github.com/gtalarico/pyairtable/issues/230), [231](https://github.com/gtalarico/pyairtable/issues/231))
  - [List bases](https://airtable.com/developers/web/api/list-bases)
  - [Get base schema](https://airtable.com/developers/web/api/get-base-schema)
  - [List views](https://airtable.com/developers/web/api/list-views)
  - [Get view metadata](https://airtable.com/developers/web/api/get-view-metadata)
  - [Get base collaborators](https://airtable.com/developers/web/api/get-base-collaborators)
  - [Get interface](https://airtable.com/developers/web/api/get-interface)
- [x] Metadata: Read collaborations/sharing
  - [Get workspace collaborators](https://airtable.com/developers/web/api/get-workspace-collaborators)
  - [List shares](https://airtable.com/developers/web/api/list-shares)
- [x] Metadata: Modify base, table, field schemas (see [235](https://github.com/gtalarico/pyairtable/issues/235), [237](https://github.com/gtalarico/pyairtable/issues/237))
  - [x] [Update field](https://airtable.com/developers/web/api/update-field)
  - [x] [Create field](https://airtable.com/developers/web/api/create-field)
  - [x] [Update table](https://airtable.com/developers/web/api/update-table)
  - [x] [Create table](https://airtable.com/developers/web/api/create-table)
  - [x] [Create base](https://airtable.com/developers/web/api/create-base)
  - [x] [Delete view](https://airtable.com/developers/web/api/delete-view)
  - [x] [Delete base](https://airtable.com/developers/web/api/delete-base)
  - [x] [Delete workspace](https://airtable.com/developers/web/api/delete-workspace)
  - [x] [Move base](https://airtable.com/developers/web/api/move-base)

## 2.3

- [x] [Enterprise: Audit log events](https://airtable.com/developers/web/api/audit-logs-overview)
- [x] Start using [trusted publishing](https://docs.pypi.org/trusted-publishers) for PyPI
- [x] Metadata: Modify collaborations/sharing
  - [x] [Update collaborator base permission](https://airtable.com/developers/web/api/update-collaborator-base-permission)
  - [x] [Update interface collaborator](https://airtable.com/developers/web/api/update-interface-collaborator)
  - [x] [Update workspace collaborator](https://airtable.com/developers/web/api/update-workspace-collaborator)
  - [x] [Delete base collaborator](https://airtable.com/developers/web/api/delete-base-collaborator)
  - [x] [Delete interface collaborator](https://airtable.com/developers/web/api/delete-interface-collaborator)
  - [x] [Delete workspace collaborator](https://airtable.com/developers/web/api/delete-workspace-collaborator)
  - [x] [Add base collaborator](https://airtable.com/developers/web/api/add-base-collaborator)
  - [x] [Add interface collaborator](https://airtable.com/developers/web/api/add-interface-collaborator)
  - [x] [Add workspace collaborator](https://airtable.com/developers/web/api/add-workspace-collaborator)
  - [x] [Delete base invite](https://airtable.com/developers/web/api/delete-base-invite)
  - [x] [Delete interface invite](https://airtable.com/developers/web/api/delete-interface-invite)
  - [x] [Delete workspace invite](https://airtable.com/developers/web/api/delete-workspace-invite)
  - [x] [Delete share](https://airtable.com/developers/web/api/delete-share)
  - [x] [Manage share](https://airtable.com/developers/web/api/manage-share)
  - [x] [Update workspace restrictions](https://airtable.com/developers/web/api/update-workspace-restrictions)
- [ ] Enterprise: Manage users
  - [x] [Remove user from enterprise](https://airtable.com/developers/web/api/remove-user-from-enterprise)
  - [x] [Delete user by id](https://airtable.com/developers/web/api/delete-user-by-id)
  - [x] [Delete users by email](https://airtable.com/developers/web/api/delete-users-by-email)
  - [x] [Logout user](https://airtable.com/developers/web/api/logout-user)
  - [x] [Manage user](https://airtable.com/developers/web/api/manage-user)
  - [ ] [Manage user batched](https://airtable.com/developers/web/api/manage-user-batched)
  - [x] [Manage user membership](https://airtable.com/developers/web/api/manage-user-membership)

## 3.0

Next major version bump after 2.0 can be for bigger ideas.

- [x] Revisit the DSL for building Airtable formulas.
- [x] Command-line interface for retrieving (or modifying?) Airtable data and metadata.
- [x] Auto-generate ORM models from Airtable base metadata.
- [x] Testing utilities for library users to safely mock the pyAirtable API in their own tests.
- [x] Drop support for Python 3.8 ([EOL Oct '24](https://devguide.python.org/versions))

## Won't do

The following wound up being a lot more work than we'd anticipated.
- [ ] Run doctests in `pyairtable` and `docs/source` on build.

The following seem like uncommon use cases and we'll wait for another contributor to need them.

- [ ] Metadata: Manage block installations
  - [List block installations](https://airtable.com/developers/web/api/list-block-installations)
  - [Delete block installation](https://airtable.com/developers/web/api/delete-block-installation)
  - [Manage block installation](https://airtable.com/developers/web/api/manage-block-installation)
- [ ] Sync CSV data
  - [Sync CSV data](https://airtable.com/developers/web/api/post-sync-api-endpoint)

SCIM is a standard API specification that is already implemented by any vendors which need to support it, so implementing it in pyAirtable doesn't seem like a priority.

- [ ] SCIM: Manage groups/users
  - [Create group](https://airtable.com/developers/web/api/create-scim-group)
  - [Create user](https://airtable.com/developers/web/api/create-scim-user)
  - [Delete group](https://airtable.com/developers/web/api/delete-scim-group)
  - [Patch group](https://airtable.com/developers/web/api/patch-scim-group)
  - [Patch user](https://airtable.com/developers/web/api/patch-scim-user)
  - [Put group](https://airtable.com/developers/web/api/put-scim-group)
  - [Put user](https://airtable.com/developers/web/api/put-scim-user)
- [ ] SCIM: Retrieve information
  - [List groups](https://airtable.com/developers/web/api/list-scim-groups)
  - [List users](https://airtable.com/developers/web/api/list-scim-users)
  - [Get group](https://airtable.com/developers/web/api/get-scim-group)
  - [Get user](https://airtable.com/developers/web/api/get-scim-user)

**Comment by gtalarico** [comment]
Thanks for putting this together @mesozoic; this looks like a great plan.

Would 2.x be a good time to also move ORM package out of [experimental](https://pyairtable.readthedocs.io/en/latest/experimental.html) and make it officially supported?

> Auto-generate ORM models from Airtable base metadata
😍

**Comment by mesozoic** [comment]
> Would 2.x be a good time to also move ORM package out of experimental and make it officially supported?

Totally! Though guessing from the comments, it seems like plenty of folks are using it already, supported or otherwise 😁 so I'm still inclined to do a major version bump before changing the semantics, return types, etc.

**Comment by walkingpendulum** [comment]
I am so hyped for test-related features in 3.0.0 😍

**Comment by mesozoic** [comment]
> I am so hyped for test-related features in 3.0.0 😍

Great! Can you share a bit more about your use case (or existing solutions) to help inform what direction we take it?

**Comment by walkingpendulum** [comment]
we have dozen of tables, couple of them havin up to 200 fields, most of which are lookups, rollups and formulas. 

major issues with airtable development, exploitation and testing:
- no table-schema-as-a-code. people mess up with field names in UI and it break our python scripts and js automations. things get worse when limk field is renamed, it breaks all the downstream lookuos and rollups. we are also continuously discovering and fixing discrepancies between table schemes jn prod and dev tables
- generally we prefer stubs to mocks in tests. for example, we spin mongodb, rabbitmq, and moto (as a drop in replacement for s3) containers in tests. this approach is not working for pyairtable, there is no stub for airtable rest api available. which is really inconvenient, because our typical unit of logic deals with 5-10 fields, most of which are lookups and rollups (this is why I am also happy for close ORM features release), and it is a nightmare to mock, test and assert
- ORM mode (soon to be released) will cone very handy. as I mentioned, there are tons of lookups and rollups, which lead to spaghetti code without ORM mode

**Comment by mesozoic** [comment]
@walkingpendulum Your use case sounds pretty complicated! So far we've avoided the field name issues by locking down Creator privileges for the bases where we've built a lot of heavy integrations. Sounds like that might not be feasible for you.

We haven't really come up with a great solution to testing; we have a minimal "fake Airtable" that mocks out the API's basic behaviors in-memory, and for integration testing we have a "partitioning shim" that injects some extra formulas/fields into every API call so that multiple test runners can operate on a single base without interfering w/ each other (as long as there's a text field where they can store a unique ID per test run). Both are utilities we'd like to move from our repos into upstream.

**Comment by walkingpendulum** [comment]
hello, guys! it's been a long time :)

I'd like to touch base on the 3.0 feature "Testing utilities for library users to safely mock the pyAirtable API in their own tests". do you still aim for it? I am as hyped to see it as I was a year ago. 

also - great job done! we have moved from one-fits-all connector component that isolates AT API calls to ad-hoc pyairtable calls, because we realized how simple and powerful pyairtable is, and never looked back. thank you for your work.

**Comment by mesozoic** [comment]
@walkingpendulum I'd still like to move what we have upstream at some point, but it's not a high priority at the moment. I'm glad some of the other improvements to the library have worked out for you!

**Comment by acmeguy** [comment]
Is it possible for Table.get* functions to return the label/value of a Lookup field as well as the record id? 
(This is all dynamic and I can not use the ORM)

**Comment by d717an** [comment]
Is it possible to enable passing parameters to the underlying request implementation when creating the Api(token) instance? For example, I need to pass in a path to a pem file. With the requests library, I do this with a `verify=path_to_pem` parameter.

**Comment by mesozoic** [comment]
> Is it possible for Table.all() functions to return the label/value of a Lookup field as well as the record id?

@acmeguy I don't think that belongs as part of the return value for `all()`, which should only perform as many API requests as needed to fetch the requested records. We'd need to add at least two more API calls per linked record field: one to inspect the table schema to determine the linked record's table, and another to retrieve that record. I'd suggest writing your own helper function to embellish the return values of `Table.all` with additional data.

**Comment by mesozoic** [comment]
> Is it possible to enable passing parameters to the underlying request implementation when creating the Api(token) instance?

@d717an I can see this getting complicated – sometimes you want the extra request kwargs to be set on the Api instance, sometimes you want them to be per-request, etc. Pull requests welcome, if you have a clear picture for how to do this in a generic fashion.

A site-specific workaround that might work for you would be directly setting the [session variables](https://github.com/psf/requests/blob/main/src/requests/sessions.py#L426) with something like:

```python
api = Api(token)
api.session.cert = path_to_pem_file
api.session.verify = True
```

**Comment by mesozoic** [comment]
Everything worth doing in here has been merged at this point. I'm going to close this issue.

**Comment by walkingpendulum** [comment]
@acmeguy great job, thank you for you work!

**Comment by walkingpendulum** [comment]
@mesozoic great job, thank you so much for your work on this project!
